title:          Marco Pracucci
baseurl:        ""
url:            http://www.pracucci.com

paginate: 10
paginate_path: "page/:num"

highlighter: pygments

permalink: none

gems:
    - jekyll-sitemap

sass:
    sass_dir: stylesheets
