title:          Marco Pracucci
baseurl:        ""
url:            https://pracucci.com
permalink:      none
paginate:       25
paginate_path:  "page/:num"
highlighter:    pygments

exclude:
    - "Gruntfile.js"
    - "Gruntfile.credentials.js"
    - "node_modules"
    - "README.md"
    - package.json

gems:
    - jekyll-compass
    - jekyll-sitemap

assets:
    # Destination of generated assets
    dirname: assets
    baseurl: /assets/

    # Sources of assets
    sources:
        - _assets/css
        - _assets/images

    # Compressors
    # js_compressor:  uglifier
    css_compressor: sass
    cache: false

    # Versioning
    cachebust: hard

    # Gzip compression
    gzip: [ text/css, application/javascript ]
