title:          Marco Pracucci
baseurl:        ""
url:            https://pracucci.com
permalink:      none
highlighter:    pygments

exclude:
    - "Gruntfile.js"
    - "Gruntfile.credentials.js"
    - "node_modules"
    - "README.md"
    - package.json

gems:
    - jekyll-sitemap

assets:
    # Destination of generated assets
    prefix: "/assets"

    # Sources of assets
    sources:
        - _assets/css
        - _assets/images
        - _assets/audio

    # Compressors
    compress:
        css: true

    cache: false

    # Versioning
    digest: true
